# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 59dcbb4027684c020187beadd0c2fdb5a5e0051b2f0f1cc7b84b43aa3ffbc546b9e669419c9be8d0e0e9f9b79e2788ee9edc03d30d6a14c6f2048e068c997014

test:
  secret_key_base: ac21b249c7f8a6616ac2abdcd3d4eef60c2e072189452e868c3e23faedfb9c33cfae08bdf98286b581e72cce6be978ed7d08ffffa69a291babdc0af306aa2141

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
